name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout do código do repositório
    - name: Checkout code
      uses: actions/checkout@v2

    # Login no DockerHub com credenciais do GitHub Secrets
    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Build da imagem Docker
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/minha-aplicacao:latest .

    # Push da imagem para o DockerHub
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/minha-aplicacao:latest

    # Adiciona a chave SSH para acesso ao servidor remoto
    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}

    # Deploy no servidor remoto
    - name: Deploy on remote server
      run: |
        ssh -o StrictHostKeyChecking=no aluno@201.23.3.86 "
          docker pull ${{ secrets.DOCKER_USERNAME }}/minha-aplicacao:latest &&
          docker stop minha-aplicacao || true &&
          docker rm minha-aplicacao || true &&
          docker run -d -p 8081:80 --name minha-aplicacao ${{ secrets.DOCKER_USERNAME }}/minha-aplicacao:latest
        "
